const ACTOR_PANEL_SCALE = 0.75;
const ACTOR_PANEL_ORIGINAL_WIDTH_REM = 21;
const ACTOR_PANEL_TOGGLE_GAP_REM = 0.5;
const ACTOR_PANEL_WIDTH_REM = ACTOR_PANEL_ORIGINAL_WIDTH_REM * ACTOR_PANEL_SCALE;
const ACTOR_PANEL_TOGGLE_LEFT_REM =
  ACTOR_PANEL_WIDTH_REM + ACTOR_PANEL_TOGGLE_GAP_REM;

export {
  ACTOR_PANEL_ORIGINAL_WIDTH_REM,
  ACTOR_PANEL_SCALE,
  ACTOR_PANEL_TOGGLE_LEFT_REM,
  ACTOR_PANEL_WIDTH_REM,
};
